name: .NET Core

on:
  push:
    branches:
        - develop
        - feature/kestrel-proxy
    tags:
        - v* 
  pull_request:
    branches:
        - develop
  workflow_dispatch:
      
jobs:
  build:
    name: 🔨 Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: 👨‍💻 Check-out code
      uses: actions/checkout@v4

    - name: 👨‍🔧 Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x
          9.x

    - name: 🔍 Enable problem matchers
      run: echo "::add-matcher::.github/matchers/dotnet.json"

    # - name: Install DocFX
    #   if: github.ref == 'refs/heads/develop'
    #   run: choco install docfx -y

    - name: 🔨 Build 
      run: |
        dotnet build src/Unobtanium.Web.Proxy/Unobtanium.Web.Proxy.csproj --configuration Release
        dotnet build src/Unobtanium.Web.Proxy.Events/Unobtanium.Web.Proxy.Events.csproj --configuration Release
        dotnet build tests/Unobtanium.Web.Proxy.KestrelTests/Unobtanium.Web.Proxy.KestrelTests.csproj --configuration Release
        

    - name: 🧪 Test
      id: test
      shell: pwsh
      run: |
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value '## 🧪 Unit Tests'
        $outputDir = "${{github.workspace}}/coverage"
        ./tests/run-tests.ps1

    - name: 📝 Code Coverage report
      if: success() || steps.test.conclusion == 'failure'
      shell: pwsh
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.*
        reportgenerator -reports:${{github.workspace}}/coverage.net8.0.cobertura.xml -targetdir:${{github.workspace}}/report -reporttypes:MarkdownSummaryGithub -filefilters:-*.g.cs "-classfilters:-Unobtanium.Web.Proxy.Network.WinAuth.*" -verbosity:Warning
        $report = Get-Content ${{github.workspace}}/report/SummaryGithub.md -Raw
        $report = $report.Replace('# Summary', '## 📝 Code Coverage').Replace('## Coverage', '### 📝 Code Coverage details')
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $report
      env:
        REPORTGENERATOR_LICENSE: ${{ secrets.REPORTGENERATOR_LICENSE }}

    - name: 📦 Upload Code Coverage report
      if: success() || steps.test.conclusion == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{github.workspace}}\report
        if-no-files-found: ignore
        retention-days: 5

    # - name: Update Documentation
    #   if: github.ref == 'refs/heads/develop'
    #   run: docfx .github/docfx.json

    # - name: Publish Documentation
    #   if: github.ref == 'refs/heads/develop'
    #   uses: EndBug/add-and-commit@v9
    #   with:
    #     default_author: github_actions
    #     message: Update documentation
    #     committer_name: GitHub Actions
    #     committer_email: actions@github.com

  publish:
    name: 🚀 Publish
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: 👨‍💻 Check-out code
      uses: actions/checkout@v4

    - name: 👨‍🔧 Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x
          9.x

    - name: 🔍 Enable problem matchers
      run: echo "::add-matcher::.github/matchers/dotnet.json"

    - name: 📦 Package
      shell: pwsh
      run: |
        $version = $("${{ github.ref_name }}".Substring(1))
        $isPrerelease = $version -match '-(alpha|beta|rc|preview)'
        Write-Host "Version: $version"
        Write-Host "Is Prerelease: $isPrerelease"
        
        dotnet pack src/Unobtanium.Web.Proxy/Unobtanium.Web.Proxy.csproj --configuration Release -p:Version=$version -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
        dotnet pack src/Unobtanium.Web.Proxy.Events/Unobtanium.Web.Proxy.Events.csproj --configuration Release -p:Version=$version -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: 🚀 Publish
      run: |
        dotnet nuget push **/*.{nupkg,snupkg} -s https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
    
    - name: 📝 Publish summary
      shell: pwsh
      run: |
        $version = $("${{ github.ref_name }}".Substring(1));
        $isPrerelease = $version -match '-(alpha|beta|rc|preview)'
        $prereleaseText = if ($isPrerelease) { " (pre-release)" } else { "" }
        
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "## 🚀 Published$prereleaseText"
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Code [tag ${{ github.ref_name }}](https://github.com/svrooij/unobtanium-web-proxy/tree/${{ github.ref_name }}) has been published to NuGet."
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Nuget [Unobtanium.Web.Proxy $version](https://www.nuget.org/packages/Unobtanium.Web.Proxy/$version) has been published to NuGet.$prereleaseText"
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Nuget [Unobtanium.Web.Proxy.Events $version](https://www.nuget.org/packages/Unobtanium.Web.Proxy.Events/$version) has been published to NuGet.$prereleaseText"